// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkXJU5_FhxJrZT7TkmksDasZrZWPrTFOo',
    appId: '1:472732579066:web:15c4452a37b0b9d0178543',
    messagingSenderId: '472732579066',
    projectId: 'taskapp-dad01',
    authDomain: 'taskapp-dad01.firebaseapp.com',
    storageBucket: 'taskapp-dad01.appspot.com',
    measurementId: 'G-JK9H75H7SM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXD95kWNgkVor8svtKJ6SsItC6NM6ntgo',
    appId: '1:472732579066:android:45a565ed9b0a86cb178543',
    messagingSenderId: '472732579066',
    projectId: 'taskapp-dad01',
    storageBucket: 'taskapp-dad01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbsafxGODBKG5EghcV8g0Gt8GqkJ1Bhoc',
    appId: '1:472732579066:ios:67b6cb6b49d40c26178543',
    messagingSenderId: '472732579066',
    projectId: 'taskapp-dad01',
    storageBucket: 'taskapp-dad01.appspot.com',
    iosClientId: '472732579066-8i9cb48tvom4to8opovfn6qu7cpttd9g.apps.googleusercontent.com',
    iosBundleId: 'com.example.tp3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbsafxGODBKG5EghcV8g0Gt8GqkJ1Bhoc',
    appId: '1:472732579066:ios:d248d1aee8fa4ac0178543',
    messagingSenderId: '472732579066',
    projectId: 'taskapp-dad01',
    storageBucket: 'taskapp-dad01.appspot.com',
    iosClientId: '472732579066-o0gffmsspaba7asoihaih6t0s7tdo68i.apps.googleusercontent.com',
    iosBundleId: 'com.example.tp3.RunnerTests',
  );
}
